"""Write docs/STORYBOARD.md: one row per scene, cut on the measured beat at or before each row's
first sung word (or at the given instrumental time). Lyrics are filled from data/lyrics.json."""
import json
L = json.load(open('data/lyrics.json')); A = json.load(open('data/audio.json'))
beats = [b['time'] for b in A['beats']]
def cut(t):  # last beat at least 0.3 s before t
    return max([b for b in beats if b <= t - 0.3] or [0.0])
def fmt(t): return f"{int(t // 60)}:{t % 60:04.1f}"
# (start: lyric prefix or seconds, on screen, purpose, leaves, carries, where the words live)
R = [
(0.0, "Title. From the first frame the camera glides fast and low over a black basalt floor toward the gates of Hades seen from inside: two immense doors of brass, studded and banded with iron bars, bolts as thick as trees, chains drawn across them. Cold blue dark; a single hairline of warm light flickers at the seam between the doors and dust sifts down from the lintel on the piano notes.", "The fortress of death is shut and huge. We start inside it, where the dead are held.", "The camera slows under the lintel and tilts up the face of the doors into the black above.", "The seam of light; the upward tilt.", "KING OF GLORY in raised brass capitals cast across the lintel, catching the cold rim light as the camera passes under; THE GATES OF HADES stamped smaller into the iron crossbar below."),
("The Sabbath held", "Above: the garden tomb on the night of the Sabbath. A rock face cut with one low door, the great round stone rolled across it, a cord and a seal of wax across the joint; olive branches black against a moonlit sky, mist lying on the ground; nothing moves but the camera craning slowly down to the stone.", "Holy Saturday: the world holds its breath; the body lies in the tomb.", "The camera keeps sinking past the base of the stone, into the ground.", "Downward motion; the cold moonlight.", "Cut into the face of the round stone along its curve, the letters picking up moonlight in their edges as each word is sung, the wax seal sitting under the last word, tomb."),
("Below, a light", "Below: the vault of Hades. We look up from the floor of an endless black cavern; far above, the vault's rock splits along a hairline and a white-gold point of light pierces it; dust and grit stream down through the beam; on the ledges around us rows of the dead (faint cold embers in burial niches) flicker.", "Christ descends: the first light that has ever entered here.", "The beam widens and the camera lifts on it.", "The beam; the stirring embers.", "Below lies on the black floor in the first patch the beam touches; a light disturbed the dead is incised along the lip of the niche ledge and lights word by word as the beam's edge sweeps across it."),
(22.28, "The light falling through the abyss. A huge descending glory of concentric rings (the icon's mandorla, deep blue to white, with gold rays) far above, still a star, growing; below it tier on tier of burial niches climbing out of sight, every ember turning toward it; chains hanging down the walls shiver; stone dust rains from every ledge as the guitars swell.", "The power coming down: the scale of the abyss is shown only so the light can dwarf it.", "The camera rises toward the light until it flares.", "The flare; the rings of light.", "Instrumental: no words."),
(31.02, "Hades' hall: a basalt throne room carved into the root of the abyss, a seated colossus of black stone (Hades, faceless, a mouth of a cave for a chest) and, coming down a long stair from the dark, a shape of shadow and cinders (Satan) trailing smoke; the far gates glow faintly at their seam.", "The two powers of death before the confrontation.", "The shadow reaches the throne's foot.", "The cinder trail.", "Instrumental: no words; the cinders spell nothing."),
("Satan came to Hades", "Satan crosses the hall to the throne; every step leaves a scorched cinder print on the basalt; the colossus's stone shoulders lean down to listen.", "Satan's boast: he thinks he has killed Christ and brings Him as a prisoner.", "The shadow raises an arm toward the cells.", "The pointing arm; a row of cells.", "Branded into the basalt floor in cinders along Satan's path, smoking as each word lands."),
("But Hades shook", "Hades trembles: cracks run across the colossus. Memory: a single burial niche in the wall, its stone seal blown outward by one word, grave linen streaming up toward a far light, the niche left empty (Lazarus).", "Hades remembers losing Lazarus to a single word.", "Linen streams up out of frame.", "The empty niche.", "Carved into the niche's stone seal, which cracks and flies outward with the words still on its fragments."),
("If Jesus enters", "An endless corridor of cell doors in iron, rank on rank; every lock trembles; rust sifts from the hinges.", "Hades' fear: if He enters, every cell will open.", "The corridor lurches into darkness.", "The trembling locks.", "Etched into the iron bars of the nearest cell doors, each word glinting as its bar shivers."),
("Satan laughed", "Satan's laugh: the shadow swells against the vault; chains swing; dust falls through the dark in sheets.", "Satan's contempt.", "The dust parts on a faint rising glow.", "Falling dust.", "The words hang in the dust sheet, lit from below like letters in smoke."),
("The captives turned", "Wide: the tiers of the dead, thousands of faint cold embers, all turning toward a warm light growing far above; one by one they warm from blue toward gold.", "The captives turn to the light: hope begins.", "Push toward one ember on the lowest ledge.", "One ember: Adam's place.", "Along the lip of the lowest tier, lit as the warm light reaches each word."),
("Adam called to Seth", "Adam's niche: an old man's silhouette, rim-lit, seen from behind; on Seth's first word the camera turns to Seth, a younger silhouette, as he turns toward his father and lifts his open hand to him; after that exchange a drop of golden oil falls from a remembered sprig into Seth's hand and spreads toward Adam.", "Adam asks Seth to tell of the oil of mercy and its promise.", "The oil drop falls and lands.", "Gold on stone.", "Written in the golden sheen of the spreading oil on the stone floor."),
("Isaiah cried", "A scroll unrolls across the dark by itself; where it opens, its letters glow like coals.", "Isaiah: the people in darkness have seen a great light.", "The scroll rolls on into the dark.", "Glowing letters.", "Written on the scroll in glowing ink as it unrolls."),
("John said", "The Forerunner: a rim-lit silhouette of John by the Jordan's water lying black in the dark of Hades; his arm and hand point up toward the approaching light; then a dove of light descends to the water and its reflection; the water clears to show a sky.", "John who pointed to the Lamb preaches here too: the Spirit, the Father's voice.", "The dove's reflection flares.", "Water and light.", "Cut into the stable stone edge of the riverbank in the foreground, lit by the dove's light, the water moving behind; one line at a time, held sharp."),
("David cried, “I sang", "A psaltery's strings glow and quiver; behind them, out of focus, the brass gates.", "David: brass will break.", "Focus racks to the gates.", "The gates.", "Cast into the psaltery's wooden frame and lit along the strings."),
("Jeremiah said", "Footprints of light appear one by one across the black floor of Hades, walking toward us.", "God would walk among us.", "The footprints lead to the praising tiers.", "The path of light.", "The footprints reveal one continuous inscription along their path on the basalt floor; the camera tracks it at a readable angle and the whole line holds sharp through the vocal."),
("The saints broke", "Thousands of lights rise into a swirling vault of praise; the shadow backs away along a corridor, looking for an exit and finding only walls.", "The saints praise; Satan is afraid and seeks to flee.", "The shadow stops before the gates.", "The gates.", "Ringing the vault with the swirl of lights; Satan's lines scratched into the corridor walls he runs along."),
("Who is this King", "The gates from inside, huge; a voice beyond them; the first blow: light spears through every seam and rivet hole.", "The challenge of Psalm 24.", "Light pours through the seams.", "The light in the seams.", "In raised brass on the doors, lit from behind through the seams."),
("Lift up your gates", "The chorus: the doors bow inward under a pressure of light; iron bars glow white-hot and sag; through widening cracks the mandorla's rings are seen; dust and rivets fly.", "The King demands entry; death's iron gives way.", "The cracks widen with the cymbals.", "Cracks in brass.", "Cast in the brass of the doors, shining through as the light leaks through the letters themselves."),
("By His cross", "Chains across the gates burst link by link; a broken link flies back into the burial tiers, where the captives stand up in their niches as the dead arise is sung; back at the gate a cross of light burns in the seam; IC XC flares.", "The cross shatters the chains; the dead will rise; Son of Mary, Son of God.", "Pull back to the whole straining gate.", "The gate.", "On the chain links as they burst; Son of Mary, Son of God along the mandorla ring."),
("Hades cried", "Hades frantically barring: shadows drag intact reserve bars and new chains out of the hall and fasten them across the already scorched, damaged doors; bolts slam home.", "Hades tries to hold the gates.", "A side passage opens.", "Iron.", "Stamped into the bolts as they slam home."),
("A thief arrived", "In a side passage a man's silhouette bearing a cross on his back walks toward us, faintly glowing, and comes close: the broad crossbeam passes slowly across the frame, then the upright, then the beam again as he turns.", "The good thief arrives first, promised Paradise; Christ is close behind.", "He passes the camera.", "His cross.", "As he passes, his glow burns one sung line at a time into the broad, stationary wall of the passage beside him; each inscription stays sharp and lit until its line ends."),
("David cried, “Open", "David's psaltery struck; the saints rise up in the tiers; thunder: a flash through every gate seam.", "Open to the King!", "Band cuts out.", "Silence; seams glowing.", "In light along the gate seams."),
("Who is this King", "Silence, then drums: the gates seen square on, every seam glowing; the second challenge.", "The question again, louder.", "The strike.", "Strain.", "In raised brass on the doors."),
("Lift up your gates", "Chorus two: the doors bulge, cracks race, bars snap.", "The breaking is near.", "Everything holds a breath.", "Cracks.", "Cast in the brass, shining through the cracks."),
("The gates of brass", "The gates burst: Christ is outside, the camera inside Hades, as in every gate shot before; the doors burst out of their frames, torn from their hinges, and fall flat into Hades, landing crossed on the floor beneath the King as in the icon (the icon's broken gates, keys and locks scattered); the King comes through: a figure of white-gold vestments within the mandorla of blue-to-white rings and gold rays, face never shown, only light.", "Christ breaks the gates and enters in glory; the one moment of shake.", "The light floods outward.", "The flood of light.", "On the falling doors as they land crossed; human form and glory in the mandorla rings."),
("The deepest prison", "Light floods every corridor and tier; Satan staggers back, his shadow torn by it.", "The prison flooded; Satan seeks flight.", "Chains of light lash out.", "Chains of light.", "On the walls as the light washes them."),
("Christ caught", "Chains of light wrap the shadow; it is bound and handed into the stone hands of the colossus, which close; the pit lid seals.", "Satan bound and given over to Hades until the Second Coming.", "The stone settles.", "Stillness.", "On the chains of light, and carved into the colossus's stone hands."),
("Jesus crossed", "Across the ruins of the gates the light walks, calling; Adam's tomb: a stone sarcophagus whose lid slides; a hand of light grasps Adam's wrist and raises him (rim-lit silhouette); Eve kneels in red beside, raised the same way.", "Christ raises Adam and Eve, as in the Anastasis icon; the shadow of a tree falls across their sarcophagi.", "The tree's shadow.", "The tree's shadow.", "Peace to you in gold across the ruin; the other lines on the sarcophagus lids."),
("One tree", "A tree's silhouette turns into the shape of the cross; the righteous file through the broken gates, rim-lit silhouettes.", "The tree of death becomes the cross, the road to life.", "The procession moves out.", "The procession.", "Along the cross's beam."),
("They asked Him", "The cross is set into the shattered throne of death; the thief's cross stands at the threshold; the procession climbs a stair of light.", "The sign of victory; Adam's children follow Christ home.", "Rise up the stair.", "Upward light.", "Carved into the throne's broken stone."),
(345.0, "Guitar solo: flight up through the opened earth, out through the ruins and up into the dawn garden; the tomb above is open, the stone rolled away, the cord and seal broken.", "The whole movement from death to life in one flight.", "Dawn spreads.", "Dawn.", "Instrumental: no words."),
("Lift up your gates", "Final chorus, one distinct shot per line: on the gates line the fallen crossed doors far below catch the dawn light; on the iron line the last iron bar still hanging in the broken frame drops and rings on the floor; on the deathless Lord the procession climbs out of the earth into the garden; on the night line the darkness in the shaft lifts; on the chains line broken chains slide off the ledges; on the dead arise the last captives step from their niches; on Son of Mary the open tomb at sunrise; on reigns on high the whole garden goes gold.", "The victory, above and below.", "Sun rises.", "Sunrise.", "Each line on the nearest surface in that shot and in focus: the fallen doors, the falling bar, the stair the procession climbs, the shaft wall, the ledges, the niches' lintels, the rolled-away stone; never white on the bright sky."),
("Christ is risen", "Outro: on Adam rises, Adam's established rim-lit silhouette walks up out of the earth into the sunrise; on Eve comes walking, Eve in her red garment follows him into the day; then wide: Christ in white-gold leading the whole procession across the field; the final tableau, the Anastasis composition in pure light; fade.", "Christ is risen; He leads His people out of death into life.", "Fade to warm black.", "The end.", "Written in light along the path they walk."),
]
def find(p, after):
    n = lambda s: ''.join(c for c in s.lower() if c.isalnum() or c == ' ')
    for l in L['lines']:
        if l['start'] >= after and n(l['text']).startswith(n(p)): return l['start']
    raise SystemExit('no line ' + p)
starts = []; after = 0
for r in R:
    if isinstance(r[0], str): s = cut(find(r[0], after)); after = find(r[0], after) + 0.01
    else: s = r[0]
    starts.append(s)
starts[0] = 0.0
ends = starts[1:] + [A['duration']]
rows = []
for r, a, b in zip(R, starts, ends):
    ly = ' '.join('“' + l['text'].replace('“', '').replace('”', '') + '”' for l in L['lines'] if a - 0.05 <= l['start'] < b)
    rows.append(f"| {fmt(a)}–{fmt(b)} | {('Lyric: ' + ly + ' ') if ly else ''}{r[1]} | {r[2]} | {r[3]} | {r[4]} | {r[5]} |")
H = ['Time', 'On screen', 'What the moment is for', 'How it leaves', 'What carries into the next shot', 'Where the words live in the scene']
open('docs/STORYBOARD.md', 'w').write('\n'.join(['# Storyboard: King of Glory (The Gates of Hades)', '',
 'Written before any animation. One row per stretch of the song. Read the lyric column top to bottom with the sound off: the story should still come through. The last column says how the words are part of that world. The picture follows the Orthodox icon of the Resurrection (the Anastasis): Christ in a mandorla of light standing on the broken gates, Satan bound, Adam and Eve raised by the wrist, the righteous behind. No faces: people are silhouettes, hands and light; Christ is light, vestments and the mandorla.', '',
 '| ' + ' | '.join(H) + ' |', '|' + '|'.join('---' for _ in H) + '|', *rows, '']))
print(len(rows), 'rows'); [print(f'{a:7.2f}') for a in starts[:6]]
